=== filipehcds/soa-12c-assignments/SoaLabApp01/SoaLabProj01/SOA/Schemas/orders.xsd
<?xml version="1.0" encoding="windows-1252" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:po="http://schemas.medin.name/wicked/soa/lab/01/orders"
            targetNamespace="http://schemas.medin.name/wicked/soa/lab/01/orders" elementFormDefault="qualified">
  <xsd:element name="orders">
    <xsd:annotation>
      <xsd:documentation>A sample element</xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence maxOccurs="unbounded">
        <xsd:element name="order">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="row" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="item" type="xsd:string"/>
                    <xsd:element name="amount" type="xsd:int"/>
                    <xsd:element name="price" type="xsd:string"/>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
            <xsd:attribute name="date" type="xsd:dateTime"/>
            <xsd:attribute name="number" type="xsd:long"/>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== filipehcds/soa-12c-assignments/collateral/sample-order.xml
<?xml version="1.0" encoding="UTF-8" ?>
<orders xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://schemas.medin.name/wicked/soa/lab/01/orders ../SoaLabApp01/SoaLabProj01/SOA/Schemas/orders.xsd"
        xmlns="http://schemas.medin.name/wicked/soa/lab/01/orders">
  <order number="123" date="2015-05-20T01:01:01">
    <row>
      <item>76042: The Shield Helicarrier</item>
      <amount>10</amount>
      <price>3499,00</price>
    </row>
    <row>
      <item>10234: Sydney Opera House</item>
      <amount>7</amount>
      <price>3199,00</price>
    </row>
    <row>
      <item>10234: The Tumbler</item>
      <amount>2</amount>
      <price>2199,00</price>
    </row>
  </order>
</orders>
